### ISSUE TITLE
Problem undertanding the _encoded parameter of setConfig()

### ISSUE THREAD

**Issue by ferru97** [smartcontractkit/libocr#28]
Hi

I'm setting up a test OCR job but I can't figure out what value the **_encode** parameter of the _setConfig()_ function of the _OffChainAggregator.sol_ contract wants. Reading the contract's comment I see _encoded off-chain oracle configuration_, but I can't understand what it is.
Any suggestions?

https://github.com/smartcontractkit/libocr/blob/d12971936c1289ae0d512723a9e8535ce382ff6d/contract/OffchainAggregator.sol#L166

Thanks

**Comment by Yiheng-Liu** [comment]
Hi, have you made any progress on the issue?

**Comment by ferru97** [comment]
Hi @Yiheng-Liu,
Actually I ended up doing reverse engeneering of the Chainlink Go framework and creating a Go script that generates the config.
If can help, I can give it to you.

**Comment by Yiheng-Liu** [comment]
Yes, this is really helpful to me. My email is [liuyiheng.cool@gmail.com](mailto:liuyiheng.cool@gmail.com), if it's convenient, please send it to my email. Thanks a lot.
